version: '3.7'

services:
    app:
        image: gostartups/blockbook-bitcoin:latest
        restart: always
        ports:
            - '9130:9130'
        volumes:
            - ~/blockbook/BTC/chain:/root/.bitcoin
            - ~/blockbook/BTC/data:/home/blockbook/data
