name: Create and publish the blockbook's containers
on:
  push:
    branches: ['master']
  schedule: 
    - cron: "0 0 2 * *"
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag for this image build'
        required: true
        default: 'latest'
    
jobs:
  build_blockbook: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "blockbook-docker"
            context: ./
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: martinkey
          password: ${{ secrets.SECRET }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: gostartups/${{ matrix.name }}:latest
      - 
        name: Build and push with Tag
        uses: docker/build-push-action@v2
        if: 
          ${{ github.event.input.image_tag != null }}
        with:
          context: ${{ matrix.context }}
          push: true
          tags: gostartups/${{ matrix.name }}:${{ github.event.inputs.image_tag }}
          
  build_blockbook_for_coins:
#     needs: build_blockbook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "blockbook-bitcoin"
            context: "./Bitcoin"
          - name: "blockbook-bitcoin-testnet"
            context: "./Bitcoin_Testnet"
          - name: "blockbook-litecoin"
            context: "./Litecoin"
          - name: "blockbook-dogecoin"
            context: "./Dogecoin"
          - name: "blockbook-ethereum"
            context: "./Ethereum"
          - name: "blockbook-bitcoingold"
            context: "./BitcoinGold"
          - name: "blockbook-bitcoingold-testnet"
            context: "./BitcoinGold_Testnet"
          - name: "blockbookonly-bitcoin"
            context: "./BlockbookOnly/Bitcoin"
          - name: "blockbookonly-bitcoin-testnet"
            context: "./BlockbookOnly/Bitcoin_Testnet"
          - name: "blockbookonly-litecoin"
            context: "./BlockbookOnly/Litecoin"
          - name: "blockbookonly-dogecoin"
            context: "./BlockbookOnly/Dogecoin"
          - name: "blockbookonly-ethereum"
            context: "./BlockbookOnly/Ethereum"
          - name: "blockbookonly-bitcoingold"
            context: "./BlockbookOnly/BitcoinGold"
          - name: "blockbookonly-bitcoingold-testnet"
            context: "./BlockbookOnly/BitcoinGold_Testnet"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: martinkey
          password: ${{ secrets.SECRET }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: gostartups/${{ matrix.name }}:latest
      - 
        name: Build and push with Tag
        uses: docker/build-push-action@v2
        if: 
          ${{ github.event.input.image_tag != null }}
        with:
          context: ${{ matrix.context }}
          push: true
          tags: gostartups/${{ matrix.name }}:${{ github.event.inputs.image_tag }}
